/**
 * Types for the Proposals admin page — autonomous self-improvement
 * proposals generated by Gilbert based on observed activity. Mirrors
 * the record shape persisted by ``ProposalsService`` on the backend.
 */

export type ProposalStatus =
  | "proposed"
  | "approved"
  | "rejected"
  | "implemented"
  | "archived";

export type ProposalKind =
  | "new_plugin"
  | "modify_plugin"
  | "remove_plugin"
  | "new_service"
  | "remove_service"
  | "config_change"
  | "modify_core";

export interface ProposalEvidence {
  event_type: string;
  summary: string;
  occurred_at: string;
  count: number;
}

export interface ProposalRisk {
  category: string;
  description: string;
  mitigation: string;
}

export interface ProposalNote {
  author_id: string;
  note: string;
  added_at: string;
}

/** The detailed spec object — kept loose because the AI may emit
 *  additional fields. The page renders it as YAML/JSON for the admin. */
export type ProposalSpec = Record<string, unknown>;

export interface ProposalImpact {
  affected_components?: string[];
  breaking_changes?: string[];
  migration_steps?: string[];
}

export interface Proposal {
  _id: string;
  id: string;
  title: string;
  summary: string;
  kind: ProposalKind | string;
  target: string;
  status: ProposalStatus | string;
  motivation: string;
  evidence: ProposalEvidence[];
  spec: ProposalSpec;
  implementation_prompt: string;
  impact: ProposalImpact;
  risks: ProposalRisk[];
  acceptance_criteria: string[];
  open_questions: string[];
  admin_notes: ProposalNote[];
  ai_profile_used: string;
  reflection_cycle_id: string;
  created_at: string;
  updated_at: string;
}

export interface ProposalsListResult {
  proposals: Proposal[];
  available_statuses: string[];
  available_kinds: string[];
}

/** One row in the cycle-history view: each manual or scheduled
 *  reflection / harvest run records its outcome into ``proposal_cycles``. */
export interface ProposalCycle {
  _id: string;
  id: string;
  kind: "reflection" | "harvest";
  manual: boolean;
  status: "ok" | "error" | "skipped" | "running";
  started_at: string;
  ended_at: string;
  skip_reason: string;
  error: string;
  observations_considered: number;
  proposals_created: number;
  conversations_processed: number;
  observations_extracted: number;
}

export interface ProposalsListCyclesResult {
  cycles: ProposalCycle[];
}
